services:
  - type: web
    name: react-news-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 20.19.0
    envVars:
      - key: GNEWS_API_KEY
        sync: false